package tun

import (
	"fmt"
	"net/netip"
	"strings"
)

// This file holds pure helpers (command argument builders and output
// parsers) used by the linux and darwin executors. They carry no build tag so
// they can be unit tested on any OS.

// gateway describes the original default route of one address family.
type gateway struct {
	ip  string // next hop, may be empty for point-to-point links
	dev string // outgoing interface, may be empty
}

func (g gateway) valid() bool { return g.ip != "" || g.dev != "" }

// parseLinuxDefaultRoute parses `ip [-6] route show default`.
func parseLinuxDefaultRoute(out string) gateway {
	for _, line := range splitLines(out) {
		f := splitFields(line)
		if len(f) == 0 || f[0] != "default" {
			continue
		}
		var g gateway
		for i := 0; i+1 < len(f); i++ {
			switch f[i] {
			case "via":
				g.ip = f[i+1]
			case "dev":
				g.dev = f[i+1]
			}
		}
		if g.valid() {
			return g
		}
	}
	return gateway{}
}

// parseDarwinDefaultRoute parses `route -n get [-inet6] default`.
func parseDarwinDefaultRoute(out string) gateway {
	var g gateway
	for _, line := range splitLines(out) {
		f := splitFields(line)
		if len(f) < 2 {
			continue
		}
		switch f[0] {
		case "gateway:":
			g.ip = f[1]
		case "interface:":
			g.dev = f[1]
		}
	}
	if strings.HasPrefix(strings.ToLower(g.ip), "fe80:") && !strings.Contains(g.ip, "%") && g.dev != "" {
		g.ip += "%" + g.dev
	}
	// "link#N" style gateways are not usable as a next hop.
	if strings.HasPrefix(g.ip, "link#") {
		g.ip = ""
	}
	return g
}

// linuxRouteArgs builds the arguments for `ip` for one route.
// verb is "add" or "del".
func linuxRouteArgs(r route, verb, tunName string, gw gateway) ([]string, error) {
	var args []string
	if r.prefix.Addr().Is6() {
		args = append(args, "-6")
	}
	args = append(args, "route", verb, r.prefix.String())
	if r.viaTun {
		return append(args, "dev", tunName), nil
	}
	if !gw.valid() {
		return nil, fmt.Errorf("no original default gateway known for %s", r.prefix)
	}
	if gw.ip != "" {
		args = append(args, "via", gw.ip)
	}
	if gw.dev != "" {
		args = append(args, "dev", gw.dev)
	}
	return args, nil
}

// darwinRouteArgs builds the arguments for `route` for one route.
func darwinRouteArgs(r route, verb, tunName string, gw gateway) ([]string, error) {
	args := []string{"-n", verb}
	if r.prefix.Addr().Is6() {
		args = append(args, "-inet6")
	}
	args = append(args, "-net", r.prefix.String())
	if r.viaTun {
		return append(args, "-interface", tunName), nil
	}
	switch {
	case gw.ip != "":
		args = append(args, gw.ip)
	case gw.dev != "":
		args = append(args, "-interface", gw.dev)
	default:
		return nil, fmt.Errorf("no original default gateway known for %s", r.prefix)
	}
	return args, nil
}

// resolvConfFor renders the replacement /etc/resolv.conf.
func resolvConfFor(dns string) string {
	return "# generated by Obsidian VPN; original saved in /etc/resolv.conf.obsidian-backup\nnameserver " + dns + "\n"
}

// parseNetworkServices parses `networksetup -listallnetworkservices`,
// dropping the header line and disabled ("*"-prefixed) services.
func parseNetworkServices(out string) []string {
	var res []string
	for _, line := range splitLines(out) {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "*") || strings.HasPrefix(line, "An asterisk") {
			continue
		}
		res = append(res, line)
	}
	return res
}

// parseDNSServers parses `networksetup -getdnsservers <svc>`.
func parseDNSServers(out string) []string {
	if strings.Contains(out, "aren't any DNS Servers") {
		return nil
	}
	var res []string
	for _, line := range splitLines(out) {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if _, err := netip.ParseAddr(line); err != nil {
			continue
		}
		res = append(res, line)
	}
	return res
}

// setDNSArgs builds `networksetup -setdnsservers <svc> <servers...|Empty>`.
func setDNSArgs(service string, servers []string) []string {
	args := []string{"-setdnsservers", service}
	if len(servers) == 0 {
		return append(args, "Empty")
	}
	return append(args, servers...)
}
